# Ejercicio resuelto del tema de Regresión

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [ ]:
# Importamos un dataset de los precios de las casas en Boston
#from sklearn import datasets ## imports datasets from scikit-learn
#data = datasets.load_boston() ## loads Boston dataset from datasets library

In [ ]:
# define the data/predictors as the pre-set feature names
#df = pd.DataFrame(data.data, columns=data.feature_names)

# Put the target (housing value -- MEDV) in another DataFrame
#target = pd.DataFrame(data.target, columns=["MEDV"])

In [ ]:
# Importamos un dataset de los precios de las casas en Boston
df = pd.read_csv("HousingData.csv")

In [ ]:
df = df.dropna()

In [ ]:
target =  df.iloc[:, -1]

In [ ]:
df = df.iloc[:, 0:13]
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222   
5    0.02985   0.0   2.18   0.0  0.458  6.430  58.7  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
499  0.17783   0.0   9.69   0.0  0.585  5.569  73.5  2.3999    6  391   
500  0.22438   0.0   9.69   0.0  0.585  6.027  79.7  2.4982    6  391   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889    1  273   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
5       18.7  394.12   5.21  
..       ...     ...    ...  
499     19.2  395.77  15.10  
500     19.2  396.90  14.33  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  

[394 rows x 13 columns]

In [ ]:
'''Muestra las primeras filas del dataframe df y target'''
df.head(5)


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222     18.7   
5  0.02985   0.0   2.18   0.0  0.458  6.430  58.7  6.0622    3  222     18.7   

        B  LSTAT  
0  396.90   4.98  
1  396.90   9.14  
2  392.83   4.03  
3  394.63   2.94  
5  394.12   5.21

In [ ]:
target.head(5)

0    24.0
1    21.6
2    34.7
3    33.4
5    28.7
Name: MEDV, dtype: float64

In [ ]:
X = df.to_numpy()

In [ ]:
y = target.to_numpy()

In [ ]:
''' Crea un modelo de regresión lineal y entrénalo '''
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, y)
''' Prueba a entrenarlo con df y target en lugar de X e y '''
model.fit(df, target)

LinearRegression()

In [ ]:
''' Predice el precio de una vivienda con los siguintes datos
0.03731	0.0	7.07	0.0	0.469	6.421	23.5	4.9671	2.0	242.0	17.8	396.90 9.14
NOTA: se corresponde con la segunda vivienda, pero con la edad de 23.5 años en lugar de 78.9'''


' Predice el precio de una vivienda con los siguintes datos\n0.03731\t0.0\t7.07\t0.0\t0.469\t6.421\t23.5\t4.9671\t2.0\t242.0\t17.8\t396.90 9.14\nNOTA: se corresponde con la segunda vivienda, pero con la edad de 23.5 años en lugar de 78.9'

In [ ]:
X_test = np.array([[0.02731,	0.0,	7.07,	0.0,	0.469,	6.421,	23.5,	4.9671,	2.0,	242.0,	17.8,	396.90, 9.14]])

In [ ]:
X_test.shape

(1, 13)

In [ ]:
model.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([25.48844759])

In [ ]:
''' ¿Cuál es el coeficiente de determinación R2? y MSE?'''

from sklearn import metrics
y_pred = model.predict(X)
print('R2:', metrics.r2_score(y, y_pred))
print('MSE:', metrics.mean_squared_error(y, y_pred))

R2: 0.767114948467778
MSE: 19.418397930734912


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [ ]:
''' Muestra los coeficientes y el punto de corte (intercept) '''
model.coef_

array([-9.75937645e-02,  4.89049306e-02,  3.03789814e-02,  2.76937811e+00,
       -1.79690282e+01,  4.28325195e+00, -1.29907658e-02, -1.45850997e+00,
        2.85865617e-01, -1.31464154e-02, -9.14582415e-01,  9.65574144e-03,
       -4.23660746e-01])

In [ ]:
model.intercept_

32.680058543306174

# Vamos a comparar el resultado de realizar una regresión lineal sin normalización y con normalización

## 1. Primero sin normalizar

In [ ]:
''' Divide el dataset en entrenamiento y test. Usa el 30% para test.
Utiliza random_state para poder ejecutar varias veces y obtener los mismos datos aleatorios y poder comparar'''

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.30, random_state=42)


In [ ]:
''' Crea el modelo de Regresión lineal y entrénalo con el conjunto de entrenamiento '''
modeloLineal = linear_model.LinearRegression()
modeloLineal.fit(X_train, y_train)

LinearRegression()

In [ ]:
''' Calcula y_pred del conjunto de test '''
Y_pred = modeloLineal.predict(X_test)

In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt


In [ ]:
''' Muestra los valores de R2 y MSE para el conjunto de test '''
print(metrics.r2_score(y_test, Y_pred))
metrics.mean_squared_error(y_test, Y_pred)

0.6905175764205985


28.870771928253543

## 2. Ahora normalizando

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [ ]:
''' Crea un escalador StandardScaler
y aplícalo sobre X_train y X_test'''
escalador = StandardScaler()
X_train_std = escalador.fit_transform(X_train)
X_Test_std = escalador.transform(X_test)


In [ ]:
from os import XATTR_CREATE
''' Crea un modelo de Regresión lineal. Llámalo modelo2 y entrénalo con los datos normalizados '''

modelo2 = linear_model.LinearRegression()
modelo2.fit(X_train_std, y_train)

LinearRegression()

In [ ]:
''' calcula y_pred2 a partir de los datos de test normalizados '''
Y_pred2 = modelo2.predict(X_Test_std)
Y_pred2

array([29.48758967, 16.89843072, 21.88395113, 30.03140416, 18.33998157,
       34.41717332, 22.29567579, 30.18541478, 32.68800811, 15.15148614,
       22.00937236, 40.89756783, 21.39760824, 16.631487  , 18.56021823,
       20.16135634, 17.03230083, 15.23458095, 22.21007405, 14.03864948,
       18.38308584, 20.31978106, 16.70540425, 29.04732153, 25.84896274,
       16.21750987, 26.91521769, 31.48625718, 23.80195772, 26.88649048,
       40.79205858, 17.93939578, 21.74000234, 17.0218407 , 17.45215081,
       20.87478891, 22.15708989, 21.38558618, 23.05850448, 21.06608939,
       27.72449001, 34.81400202, 21.78651421, 30.44288708, 34.59722541,
       19.75813031, 24.68728038, 10.22457273, 19.81849411, 25.15817576,
       21.82205121, 25.58520471, 14.76531893, 18.31754995, 18.17045495,
       23.96198129, 43.37418034, 22.39050206, 15.68056608, 23.22677962,
       20.98939499, 21.55059106, 14.59407927, 28.87042011, -3.45096729,
       32.51557282, 16.5500498 , 31.10947226, 24.8731608 , 20.17

In [ ]:
''' Calcula las mátricas R2 y MSE y comprueba si ha habido mejora '''
print(metrics.r2_score(y_test, Y_pred2))
metrics.mean_squared_error(y_test, Y_pred2)

0.6905175764205997


28.87077192825343